@startuml
start
:管理员登录并进入文件管理页面;
:选择文件清理或文件删除功能;
if (文件清理?) then (是)
  :扫描系统文件;
  :识别违规文件;
  :删除违规文件;
elseif (文件删除?) then (是)
  :选择目标文件;
  :提交删除请求;
  :删除选定文件;
else (退出管理)
endif
:更新数据库记录;
:返回操作成功提示;
stop
@enduml
