@startuml
start
:用户选择操作;
if (注册?) then (是)
  :输入邮箱和密码;
  :校验邮箱格式;
  if (邮箱唯一?) then (是)
    :生成验证码;
    :完成注册;
  else (否)
    :提示邮箱已被注册;
  endif
elseif (登录?) then (是)
  :输入邮箱和密码;
  :校验邮箱和密码;
  if (认证成功?) then (是)
    :生成JWT令牌;
    :登录成功;
  else (否)
    :提示认证失败;
  endif
elseif (忘记密码?) then (是)
  :输入邮箱;
  :发送验证码;
  :输入验证码;
  if (验证码有效?) then (是)
    :重置密码;
    :提示成功;
  else (否)
    :提示验证码无效;
  endif
else (否)
  :退出;
endif
stop
@enduml
