@startuml
start
:用户选择操作;
if (文件上传?) then (是)
  :选择文件;
  :判断是否支持秒传;
  if (支持秒传?) then (是)
    :更新数据库记录;
    :上传完成;
  else (否)
    :分片上传;
    :记录分片进度;
    :合并分片;
  endif
elseif (文件下载?) then (是)
  :选择文件;
  :生成下载链接;
  :传输文件至浏览器;
elseif (文件删除?) then (是)
  :移动文件至回收站;
  :更新数据库记录;
elseif (文件重命名/移动?) then (是)
  :更新文件元信息;
elseif (文件预览?) then (是)
  :解析文件内容;
  :返回文件数据至前端;
else (退出操作)
endif
stop
@enduml
