@startuml
start
:用户选择操作;
if (获取分享文件列表?) then (是)
  :发送获取文件列表请求至后端;
  :后端查询数据库中的分享文件信息;
  :返回分享文件列表给用户;
elseif (分享文件?) then (是)
  :用户选择文件并提交分享请求;
  :生成唯一分享链接;
  :存储分享信息至数据库;
  :返回分享链接给用户;
elseif (取消分享?) then (是)
  :发送取消分享请求至后端;
  :后端更新分享记录状态为取消;
else (退出操作)
endif
stop
@enduml
